import { Timetable } from '@/hooks/server/useTimetableData.ts';

export const timetableAPIDummies: Timetable = {
  timetableId: 1,
  timetableName: '새 시간표',
  semester: '2025-1',
  schedules: [
    {
      scheduleId: 1,
      scheduleType: 'official',
      subjectId: 2562,
    },
    {
      scheduleId: 2,
      scheduleType: 'custom',
      subjectName: '캡스톤 디자인',
      professorName: '박교수',
      location: '산학협력관 102호',
      dayOfWeek: ['화', '목'],
      startTime: '16:00',
      endTime: '18:50',
    },
    {
      scheduleId: 3,
      scheduleType: 'custom',
      subjectName: '알고리즘',
      professorName: '김교수',
      location: '센B201',
      dayOfWeek: ['월', '수', '금'],
      startTime: '09:00',
      endTime: '10:30',
    },
    {
      scheduleId: 4,
      scheduleType: 'custom',
      subjectName: '컴퓨터네트워크',
      professorName: '최교수',
      location: '센B209',
      dayOfWeek: ['화', '목'],
      startTime: '10:40',
      endTime: '12:10',
    },
    {
      scheduleId: 5,
      scheduleType: 'custom',
      subjectName: '소프트웨어공학',
      professorName: '정교수',
      location: '센B210',
      dayOfWeek: ['월', '수', '금'],
      startTime: '13:00',
      endTime: '14:30',
    },
    {
      scheduleId: 6,
      scheduleType: 'custom',
      subjectName: '알바',
      professorName: '',
      location: '카페',
      dayOfWeek: ['화', '목'],
      startTime: '18:50',
      endTime: '22:00',
    },
  ],
};
