name: ALLCLL Production CI/CD
on:
  push:
    branches: [main]

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Allow one concurrent deployment
concurrency:
  group: 'pages'
  cancel-in-progress: true

jobs:
  client-deploy:
    name: build
    runs-on: ubuntu-latest
    env:
      working-directory: ./
      project-directory: ./packages/client

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '24'

      - name: Install NPM packages
        run: |
          npm install -g pnpm
          pnpm i --frozen-lockfile
        working-directory: ${{env.working-directory}}

      - name: Build Client project
        run: |
          pnpm run build-client
          cd ${{env.project-directory}}
        env:
          CI: ''
          SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}
          VITE_SENTRY_DSN: ${{ secrets.SENTRY_DSN }}
          VITE_GOOGLE_ANALYTICS_ID: ${{ secrets.GOOGLE_ANALYTICS_ID }}
          VITE_CLARITY_PROJECT_ID: ${{ secrets.CLARITY_PROJECT_ID }}
          VITE_API_BASE_URL: ${{ secrets.API_BASE_URL }}
          VITE_DEV_SERVER: false
        working-directory: ${{env.working-directory}}

      - name: Upload production-ready build files
        uses: actions/upload-artifact@v4
        with:
          name: production-files
          path: ${{env.project-directory}}/dist

      - name: Delete unused files
        run: |
          rm -rf ${{env.project-directory}}/dist/report.html

      # Deployment
      - name: Deploy to S3
        uses: jakejarvis/s3-sync-action@master
        with:
          args: --acl public-read --delete
        env:
          AWS_S3_BUCKET: ${{ secrets.MAIN_AWS_BUCKET_NAME }}
          AWS_ACCESS_KEY_ID: ${{ secrets.MAIN_AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.MAIN_AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: ${{ secrets.MAIN_AWS_DEFAULT_REGION }}
          SOURCE_DIR: ${{env.project-directory}}/dist

      - name: Invalidate CloudFront
        uses: chetan/invalidate-cloudfront-action@master
        env:
          PATHS: '/*'
          AWS_ACCESS_KEY_ID: ${{ secrets.MAIN_AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.MAIN_AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: ${{ secrets.MAIN_AWS_DEFAULT_REGION }}
          DISTRIBUTION: ${{ secrets.MAIN_AWS_DISTRIBUTION_ID }}
