name: PR CI

on:
  pull_request:
    branches: [main, develop]

permissions:
  contents: read

jobs:
  build-and-lint:
    runs-on: ubuntu-latest
    env:
      working-directory: ./

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '24'

      - name: Install pnpm
        run: npm install -g pnpm

      - name: Install dependencies
        run: pnpm i --frozen-lockfile
        working-directory: ${{ env.working-directory }}

      - name: Lint
        run: pnpm --filter @allcll/client lint && pnpm --filter @allcll/admin lint
        working-directory: ${{ env.working-directory }}

      - name: Build Client
        run: pnpm run build-client
        working-directory: ${{ env.working-directory }}

      - name: Build Admin
        run: pnpm run build-admin
        working-directory: ${{ env.working-directory }}
